config/routes.rb
Rails.application.routes.draw do

  root "public#index"

  resources :subjects do
    member do
      get :delete
    end
    resources :pages do
      member do
        get :delete
      end
      resources :sections do
        member do
          get :delete
        end
      end
    end
  end





  resources :admin_users, except: [:show] do
    member do
    get :delete
    end
  end

  get "show/:permalink", to: "public#show"
  get "admin", to: "access#index"

  # catch all, default route match
  match ":controller(/:action(/:id(.:format)))", via: [:get, :post]
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  layout "admin"

  before_action :confirm_logged_in, except: [:login, :attempt_login, :logout]

  def index
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user

      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username

      flash[:notice] = "#{authorized_user.username} successfully logged in."
      redirect_to(action: "index")
    else
      flash[:notice] = "Invalid Username / Password combination"
      redirect_to(action: "login")
    end
  end

  def logout
    session[:user_id] = nil
    session[:username] = nil

    flash[:notice] = "Logged Out"
    redirect_to(action: "login")
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/index.html.erb
<% @page_title = "Admin Menu" %>

<div class="menu">
  <h2>Admin Menu</h2>
  <div class="identity">Logged in as: <%= session[:username] %></div>
  <ul>
    <li><%= link_to("Manage Content", subjects_path) %></li>
    <li><%= link_to("Manage Admin Users", admin_users_path) %></li>
    <li><%= link_to("Logout", :action => 'logout') %></li>
  </ul>
</div>

app/views/access/login.html.erb
<% @page_title = "Admin Login" %>

<div class="login">
  <%= form_tag(:action => 'attempt_login') do %>
    <table>
      <tr>
        <td><%= label_tag(:username) %></td>
        <td><%= text_field_tag(:username) %></td>
      </tr>
      <tr>
        <td><%= label_tag(:password) %></td>
        <td><%= password_field_tag(:password) %></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><%= submit_tag("Log In") %></td>
      </tr>
    </table>
  <% end %>
</div>