config/routes.rb
Rails.application.routes.draw do

  root "public#index"

  resources :subjects do
    member do
      get :delete
    end
    resources :pages do
      member do
        get :delete
      end
      resources :sections do
        member do
          get :delete
        end
      end
    end
  end





  resources :admin_users, except: [:show] do
    member do
    get :delete
    end
  end

  get "show/:permalink", to: "public#show"
  get "admin", to: "access#index"

  # catch all, default route match
  match ":controller(/:action(/:id(.:format)))", via: [:get, :post]
end

app/views/pages/_form.html.erb
<%= error_messages_for(@page) %>

<table summary="Page form fields">
  <tr>
    <th><%= f.label(:subject_id, "Subject") %></th>
    <td><%= f.select(:subject_id, @subjects.map {|s| [s.name, s.id]}) %></td>
  </tr>
  <tr>
    <th><%= f.label(:name, "Name") %></th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:permalink) %></th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th><%= f.label(:position) %></th>
    <td><%= f.select(:position, 1..@page_count) %></td>
  </tr>
  <tr>
    <th><%= f.label(:visible) %></th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
</table>

app/views/pages/delete.html.erb
<% @page_title = "Delete '#{@page.name}'" %>

<%= link_to("<< Back to List", {:action => 'index', :subject_id => @subject.id}, :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>

  <%= form_for(:page, :url => {:action => 'destroy', :id => @page.id}) do %>

    <p>Are you sure you want to permanently delete this page?</p>

    <p class="reference-name"><%= @page.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete Page") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<% @page_title = "Edit '#{@page.name}'" %>

<%= link_to("<< Back to List", {:action => 'index', :subject_id => @subject.id}, :class => 'back-link') %>

<div class="pages edit">
  <h2>Update Page</h2>

  <%= form_for(:page, :url => {:action => 'update', :id => @page.id}) do |f| %>

    <%= render(:partial => "form", :locals => { :f => f }) %>

    <div class="form-buttons">
      <%= submit_tag("Edit Page") %>
    </div>

  <% end %>
</div>

app/views/pages/index.html.erb
<% @page_title = "Pages" %>

<%= link_to("<< Back to Menu", {:controller => 'access', :action => 'index'}, :class => 'back-link') %>
<%= link_to("<< Back to Subjects", subjects_path, :class => 'back-link') %>

<div class="pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page", new_subject_page_path(:subject_id => @subject.id), :class => 'action new') %>

  <div><%= pluralize(@pages.size, 'page') %> found</div>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>&nbsp;</th>
      <th>Subject</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= page.position %></td>
        <td><%= page.subject.name if page.subject %></td>
        <td><%= page.name %></td>
        <td><%= page.permalink %></td>
        <td class="center"><%= status_tag(page.visible) %></td>
        <td class="center"><%= page.sections.size %></td>
        <td class="actions">
          <%= link_to("View Sections", { :controller => 'sections', :page_id => page.id }, :class => 'action show') %>
          <%= link_to("Show", subject_page_path(page.id, subject_id: @subject.id), :class => 'action show') %>
          <%= link_to("Edit", edit_subject_page_path(page.id, :subject_id => @subject.id), :class => 'action edit') %>
          <%= link_to("Delete", delete_subject_page_path(page.id, :subject_id => @subject.id), :class => 'action delete') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<% @page_title = "New Page" %>

<%= link_to("<< Back to List", {:action => 'index', :subject_id => @subject.id}, :class => 'back-link') %>

<div class="pages new">
  <h2>Create Page</h2>

  <%= form_for(:page, :url => {:action => 'create', :subject_id => @subject.id}) do |f| %>

    <%= render(:partial => "form", :locals => { :f => f }) %>

    <div class="form-buttons">
      <%= submit_tag("Create Page") %>
    </div>

  <% end %>
</div>

app/views/pages/show.html.erb
<% @page_title = "#{@page.name}'" %>

<%= link_to("<< Back to List", {:action => 'index', :subject_id => @subject.id}, :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>

  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>