config/routes.rb
Rails.application.routes.draw do

  root "public#index"

  resources :subjects do
    member do
      get :delete
    end
    resources :pages do
      member do
        get :delete
      end
      resources :sections do
        member do
          get :delete
        end
      end
    end
  end





  resources :admin_users, except: [:show] do
    member do
    get :delete
    end
  end

  get "show/:permalink", to: "public#show"
  get "admin", to: "access#index"

  # catch all, default route match
  match ":controller(/:action(/:id(.:format)))", via: [:get, :post]
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages, dependent: :destroy

  acts_as_list

  validates_presence_of :name
  validates_length_of :name, maximum: 255

  scope :visible, lambda { where(visible: true) }
  scope :invisible, lambda { where(visible: false) }
  scope :sorted, lambda { order("subjects.position ASC") }
  scope :newest_first, lambda { order("subjects.created_at DESC") }
  scope :search, lambda { |query|
    where(["name LIKE ?", "%#{query}%"])
  }
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout "admin"

  before_action :confirm_logged_in

  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find_by_id(params[:id])
  end

  def new
    @subject = Subject.new
    @subject_count = Subject.count + 1
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:notice] = "Subject '#{@subject.name}' created successfully"
      redirect_to(action: "index")
    else
      @subject_count = Subject.count + 1
      render("new")
    end
  end

  def edit
    @subject = Subject.find_by_id(params[:id])
    @subject_count = Subject.count
  end

  def update
    @subject = Subject.find_by_id(params[:id])

    if @subject.update(subject_params)
      flash[:notice] = "Subject '#{@subject.name}' updated successfully"
      redirect_to(action: "show", id: @subject.id)
    else
      @subject_count = Subject.count
      render("edit")
    end
  end

  def delete
    @subject = Subject.find_by_id(params[:id])
  end

  def destroy
    subject = Subject.find_by_id(params[:id]).destroy
    flash[:notice] = "Subject '#{subject.name}' deleted"
    redirect_to(action: "index")
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= error_messages_for(@subject) %>

<table summary="Subject form fields">
  <tr>
    <th><%= f.label(:name) %></th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:position) %></th>
    <td><%= f.select(:position, 1..@subject_count) %></td>
  </tr>
  <tr>
    <th><%= f.label(:visible) %></th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th><%= f.label(:created_at) %></th>
    <td><%= f.datetime_select(:created_at) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<% @page_title = "Delete '#{@subject.name}'" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>

  <%= form_for(:subject, :url => subject_path(@subject.id), :html => { :method => :delete }) do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>

    <p class="reference-name"><%= @subject.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<% @page_title = "Edit '#{@subject.name}'" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => "form", :locals => { :f => f}) %>

    <div class="form-buttons">
      <%= submit_tag("Edit Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<% @page_title = "Subjects" %>

<%= link_to("<< Back to Menu", {:controller => 'access', :action => 'index'}, :class => 'back-link') %>

<div class="subjects index">
  <h2>Subjects</h2>


  <%= link_to( image_tag('plus_sign.png', :size => '11x11', :alt => '+') + " Add New Subject", {:action => 'new'}, :class => 'action new') %>

  <div><%= pluralize(@subjects.size, 'subject') %> found</div>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>&nbsp;</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= subject.position %></td>
        <td><%= subject.name %></td>
        <td class="center"><%= status_tag(subject.visible) %></td>
        <td class="center"><%= subject.pages.size %></td>
        <td class="actions">
          <%= link_to("View Pages", { :controller => 'pages', :subject_id => subject.id }, :class => 'action show') %>
          <%= link_to("Show", { :action => 'show', :id => subject.id }, :class => 'action show') %>
          <%= link_to("Edit", { :action => 'edit', :id => subject.id }, :class => 'action edit') %>
          <%= link_to("Delete", { :action => 'delete', :id => subject.id }, :class => 'action delete') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<% @page_title = "New Subject" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => "form", :locals => { :f => f}) %>

    <div class="form-buttons">
      <%= submit_tag("Create Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/show.html.erb
<% @page_title = @subject.name %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>