config/routes.rb
Rails.application.routes.draw do

  root "public#index"

  resources :subjects do
    member do
      get :delete
    end
    resources :pages do
      member do
        get :delete
      end
      resources :sections do
        member do
          get :delete
        end
      end
    end
  end





  resources :admin_users, except: [:show] do
    member do
    get :delete
    end
  end

  get "show/:permalink", to: "public#show"
  get "admin", to: "access#index"

  # catch all, default route match
  match ":controller(/:action(/:id(.:format)))", via: [:get, :post]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # To configure a different table name:
  # self.table_name = "admin_users"

  has_secure_password

  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, through: :section_edits

  scope :sorted, lambda { order("admin_users.last_name ASC, admin_users.first_name ASC") }

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  # long form validations

  # validates_presence_of :first_name
  # validates_length_of :first_name, :maximum => 25
  # validates_presence_of :last_name
  # validates_length_of :last_name, :maximum => 50
  # validates_presence_of :username
  # validates_length_of :username, :within => 8..25
  # validates_uniqueness_of :username
  # validates_presence_of :email
  # validates_length_of :email, :maximum => 100
  # validates_format_of :email, :with => EMAIL_REGEX
  # validates_confirmation_of :email

  # shortcut validations, aka "sexy validations"
  validates :first_name, presence: true,
                         length: {maximum: 25}

  validates :last_name, presence: true,
                        length: {maximum: 50}

  validates :username, length: {within: 8..25},
                       uniqueness: true

  validates :email, presence: true,
                    length: {maximum: 100},
                    format: EMAIL_REGEX,
                    confirmation: true

  FORBIDDEN_USERNAMES = %w[wibble123 wobble456]

  validate :username_is_allowed
  validate :no_new_users_on_saturday, on: "create"

  def username_is_allowed
    if FORBIDDEN_USERNAMES.include?(username)
      errors.add(:username, "is not allowed")
    end
  end

  # Errors not related to a specific attribute
  # can be added to errors[:base]
  def no_new_users_on_saturday
    if Time.now.wday == 6
      errors[:base] << "No new users on Saturdays."
    end
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  layout "admin"

  before_action :confirm_logged_in

  def index
    @users = AdminUser.sorted
  end

  def new
    @user = AdminUser.new
  end

  def create
    @user = AdminUser.new(user_params)

    if @user.save
      flash[:notice] = "User '#{@user.name} - #{@user.username}' created successfully."
      redirect_to(admin_users_path)
    else
      render("new")
    end
  end

  def edit
    @user = AdminUser.find_by_id(params[:id])
  end

  def update
    @user = AdminUser.find_by_id(params[:id])

    if @user.update_attributes(user_params)
      flash[:notice] = "User '#{@user.name} - #{@user.username}' updated successfully."
      redirect_to(admin_users_path)
    else
      render("edit")
    end
  end

  def delete
    @user = AdminUser.find_by_id(params[:id])
  end

  def destroy
    user = AdminUser.find_by_id(params[:id]).destroy
    flash[:notice] = "User '#{user.username}' destroyed successfully."
    redirect_to(admin_users_path)
  end

  private

  def user_params
    params.require(:admin_user).permit(:first_name, :last_name, :email, :username, :password)
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= error_messages_for(@user) %>

<table summary="User form fields">
  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:username) %></th>
    <td><%= f.text_field(:username) %></td>
  </tr>
  <tr>
    <th><%= f.label(:email) %></th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th><%= f.label(:password) %></th>
    <td><%= f.password_field(:password) %></td>
  </tr>
  <tr>
    <th><%= f.label(:password_confirm) %></th>
    <td><%= f.password_field(:password_confirm) %></td>
  </tr>
</table>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete '#{@user.username}'" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="users delete">
  <h2>Delete User</h2>

  <%= form_for(:admin_user, :url => admin_user_path(@user.id), :html => { :method => :delete }) do |f| %>

    <p>Are you sure you want to permanently delete this User?</p>

    <p class="reference-name"><%= @user.name %> - <%= @user.username %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete User") %>
    </div>

  <% end %>
</div>

app/views/admin_users/edit.html.erb
<% @page_title = "Edit '#{@user.username}'" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="users edit">
  <h2>Update User</h2>

  <%= form_for(:user, :url => {:action => 'update', :id => @user.id}) do |f| %>

    <%= render(:partial => "form", :locals => { :f => f }) %>

    <div class="form-buttons">
      <%= submit_tag("Edit User") %>
    </div>

  <% end %>
</div>

app/views/admin_users/index.html.erb
<% @page_title = "Admin Users" %>

<%= link_to("<< Back to Menu", {:controller => 'access', :action => 'index'}, :class => 'back-link') %>


<div class="admin_users index">
  <h2>Pages</h2>

  <%= link_to("Add New Admin User", new_admin_user_path, :class => 'action new') %>

  <div><%= pluralize(@users.size, 'user') %> found</div>

  <table class="listing" summary="Admin Users list">
    <tr class="header">
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    <% @users.each do |user| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= mail_to(user.email) %></td>
        <td class="actions">
          <%= link_to("Edit", edit_admin_user_path(user.id), :class => 'action edit') %>
          <%= link_to("Delete", delete_admin_user_path(user.id), :class => 'action delete') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin_users/new.html.erb
<% @page_title = "New User" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="users new">
  <h2>Create User</h2>

  <%= form_for(@user) do |f| %>

    <%= render(:partial => "form", :locals => { :f => f}) %>

    <div class="form-buttons">
      <%= submit_tag("Create User") %>
    </div>

  <% end %>
</div>